---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  proxy:
    http: "http://pascal:80/"
    https: "http://pascal:80/"
    no_proxy: "localhost,127.0.0.1,.example.com"
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[weblogic::default]
    attributes:
      weblogic:
        remote_installation_file: "http://git-1.athens.intrasoft-intl.private/V13672-01.zip"
      java:
        install_flavor: "oracle"
        jdk_version: "6"
        arch: "x86_64"
        jdk:
          '6':
            x86_64:
              url: "http://git-1.athens.intrasoft-intl.private/jdk-6u5-linux-x64.bin"
              checksum: "772ea25e5c4d8fa48db1a4b2349e17b8b1ca033814ff28b2dd34f88255070a26"
        # oracle:
        #   accept_oracle_download_terms: true
