---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[weblogic::default]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "6"
        arch: "x86_64"
        jdk:
          "6":
            x86_64:
              url: "http://download.oracle.com/otn-pub/java/jdk/6u5b/jdk-6u5-linux-x64.bin"
              checksum: "772ea25e5c4d8fa48db1a4b2349e17b8b1ca033814ff28b2dd34f88255070a26"
        oracle:
          accept_oracle_download_terms: true
