name             'weblogic'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures weblogic'
long_description 'Installs/Configures weblogic'
version          '0.1.0'
depends          'java'
