name             'weblogic'
maintainer       'Christos Kapasakalidis'
maintainer_email 'xkapasakal@gmail.com'
license          'All rights reserved'
description      'Installs/Configures weblogic'
long_description 'Installs/Configures weblogic'
version          '0.1.0'
depends          'java'
